---
- hosts: localhost
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  tasks: 
  - name: Install boto3/botocore
    pip: 
      name: boto3
      state: present
  - name: Create S3 bucket
    s3_bucket: 
      name: sharks-terra-backend123
      state: present