---
- hosts: localhost
  tasks:
  - name: Install boto3
    pip: 
      name: 
        - boto3
        - botocore
      executable: pip3
  - name: Create S3 bucket
    s3_bucket: 
      name: sharks-terra-backend123
      state: present  