# This is a basic workflow to help you get started with Actions

name: terraform-iac

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ terraform ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
  terraform-actions:
    name: terraform-apply 
    runs-on: self-hosted

    steps: 
    - name: Checkout Repo
      uses: actions/checkout@master

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-2 

    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v1
    #   with: 
    #     terraform_version: 1.0.10

    - name: Terraform format
      id: fmt
      run: terraform fmt --check --diff
      continue-on-error: true

    - name: Initialize terraform  
      id: init
      run: terraform init -upgrade
      continue-on-error: false  

    - name: Create dev env
      if: github.ref == 'refs/head/terraform' && github.event.name == 'push'
      run: terraform workspace new dev
      continue-on-error: true

    - name: Create prod env
      if: github.ref == 'refs/head/master' && github.event.name == 'pull'
      run: terraform workspace new prod
      continue-on-error: true


    - name: Validate terraform 
      id: validate 
      run: terraform validate -no-color
      continue-on-error: false


    













